feed/urls.py
from django.urls import path
from . import views

app_name = 'feed'

urlpatterns = [
    path('', views.HomePage.as_view(), name='index'),
    path('following/', views.FollowingFeed.as_view(), name='following'),
    path('<int:pk>/', views.PostDetailPage.as_view(), name='detail'),
    path('new/', views.CreatePostPage.as_view(), name='create'),
]

til/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path
from feed import urls as feed_urls  
from profiles import urls as profile_urls  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(feed_urls, namespace='feed')),
    path('profile/',include(profile_urls, namespace='profiles')),
    path('', include('allauth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/post.html
{% load thumbnail %}
{% load static %}

<div class="max-w-4xl px-20 mx-50 my-4 py-6 bg-white rounded-lg shadow-md" style='width: 45rem'>
    <div class="flex justify-between items-center">
        <span class="font-light text-gray-600">{{ post.date|date:"F j, Y, g:i:a" }}</span>
    </div>
    <div class="mt-2">
        <p class="mt-2 text-gray-600">{{ post.text }}</p>
    </div>

    {% if detail_on %}
    <div class="flex justify-between items-center mt-4">
        <a class="text-gray-600 hover:underline" href="{% url "feed:detail" post.id %}">
            <i class='bx bxs-right-arrow-circle bx-md hover:bg-teal-200 rounded-md transition duration-150 ease-in-out' style="color: rgba(0, 200, 180)"></i>
        </a>
    {% else %}
    <div class="flex justify-between items-center mt-4">
    <span>&nbsp;</span>
    {% endif %}
        <div>
            <a class="grid grid-cols-1 gap-y-1 hover:scale-110 rounded-md transition duration-150 ease-in-out" href="{% url "profiles:detail" post.author.username %}">
                {% if post.author.profile.profile_pic %}
                    {% thumbnail post.author.profile.profile_pic "100x100" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="mx-4 w-16 h-16 object-cover rounded-full hidden sm:block" alt="avatar">
                    {% endthumbnail %}
                {% else %}
                <img src="{% static 'default.jpg' %}" width="100" height="100" class="mx-4 w-16 h-16 object-cover rounded-full hidden sm:block" alt="avatar">
                {% endif %}
                <div class="text-gray-700 text-center">
                    <h1 class="font-bold">{{post.author.username}}</h1>
                </div>
            </a>                    
        </div>
    </div>
</div>