feed/urls.py
from django.urls import path
from . import views

app_name = 'feed'

urlpatterns = [
    path('', views.HomePage.as_view(), name='index'),
    path('following/', views.FollowingFeed.as_view(), name='following'),
    path('<int:pk>/', views.PostDetailPage.as_view(), name='detail'),
    path('new/', views.CreatePostPage.as_view(), name='create'),
]

til/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path
from feed import urls as feed_urls  
from profiles import urls as profile_urls  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(feed_urls, namespace='feed')),
    path('profile/',include(profile_urls, namespace='profiles')),
    path('', include('allauth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load thumbnail %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Default{% endblock %}</title>
  {% comment %} <link rel="icon" href="{% static "default.jpg" %}" type="image/x-icon">
  <link rel="shortcut icon" href="{% static "default.jpg" %}" type="image/x-icon"> {% endcomment %}
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
  {% block style %}{% endblock %}
  <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="font-open-sans antialiased overflow-x-hidden">
  <div class="w-full bg-[url(https://neluttu.github.io/pro-profile/wallpaper.jpg)] bg-[#292240] flex">
  <div id="view" class="min-h-[599px] w-screen grid grid-cols-1 justify-items-center" x-data="{ sidenav: true }">

    <div id="sidebar"
    class="bg-white h-screen shadow-xl px-4 w-30 md:w-60 lg:w-60 overflow-x-hidden transition-transform duration-300 ease-in-out fixed left-0 top-0"
    x-show="sidenav" @click.away="sidenav = false">
      <div class="space-y-6 md:space-y-10 mt-10">
        
        <h1 class="hidden md:block font-bold text-sm md:text-xl text-center">
          TIL<span class="text-teal-600">.</span>
        </h1>
        <div id="profile" class="space-y-3 hover:bg-teal-200 hover:text-white hover:scale-110 rounded-md transition duration-150 ease-in-out">
        {% if request.user.is_authenticated %}
        <a href="{% url 'profiles:detail' request.user.username %}">
        {% endif %}
        {% if request.user.profile.profile_pic %}  
            {% thumbnail request.user.profile.profile_pic "100x100" crop="center" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
              class="w-10 md:w-16 rounded-full mx-auto" alt="Avatar user">
            {% endthumbnail %}
          {% else %}
            <img src="{% static 'default.jpg' %}" width="100" height="100" class="w-10 md:w-16 rounded-full mx-auto" alt="Avatar user">
        {% endif %}
            <div>
              <h2 class="font-medium text-xs md:text-sm text-center text-teal-500">
                {{ request.user.username }}
              </h2>
              <p class="text-xs text-gray-500 text-center">User</p>
          </div>
        </a>
      </div>
      <div id="menu" class="flex flex-col space-y-2">
        <a href="/"
          class="text-md font-medium text-gray-700 py-2 px-2 hover:bg-teal-200 hover:text-white hover:scale-110 rounded-md transition duration-150 ease-in-out"
          style="display: flex; ">
          <i class='bx bx-world bx-sm' style='color:rgba(0, 200, 180)'></i>
          <span class="">Explore</span>
        </a>
        {% if request.user.is_authenticated %}
        <a href="{% url "feed:following" %}"
          class="text-md font-medium text-gray-700 py-2 px-2 hover:bg-teal-200 hover:text-white hover:scale-110 rounded-md transition duration-150 ease-in-out"
          style="display: flex; ">
          <i class='bx bx-home bx-sm' style='color:rgba(0, 200, 180)'></i>
          <span class="">Following</span>
        </a>
        {% endif %}

        <div
          class="text-md font-medium text-gray-700 py-2 px-2 hover:bg-teal-200 hover:text-white hover:scale-110 rounded-md transition duration-150 ease-in-out modal-click"
          style="display: flex; ">
          <i class='bx bxs-message-rounded-add bx-sm' style='color:rgba(0, 200, 180)'></i>
          <span class="">Create</span>
        </div>

        {% if request.user.is_authenticated %}
        <a href="{% url 'account_logout' %}"
          class="text-md font-medium text-gray-700 py-2 px-2 hover:bg-teal-200 hover:text-white hover:scale-110 rounded-md transition duration-150 ease-in-out"
          style="display: flex; ">
          <i class='bx bx-log-out bx-sm' style='color:rgba(0, 200, 180)'></i>
          <span class="">Logout</span>
        </a>

        {% else %}
        <a href="{% url 'account_login' %}"
          class="text-md font-medium text-gray-700 py-2 px-2 hover:bg-teal-200 hover:text-white hover:scale-110 rounded-md transition duration-150 ease-in-out"
          style="display: flex; ">
          <i class='bx bx-log-in bx-sm' style='color:rgba(0, 200, 180)'></i> <span>Login</span>
        </a>

        <a href="{% url 'account_signup' %}"
          class="text-md font-medium text-gray-700 py-2 px-2 hover:bg-teal-200 hover:text-white hover:scale-110 rounded-md transition duration-150 ease-in-out"
          style="display: flex; ">
          <i class='bx bx-archive-out bx-sm' style='color:rgba(0,200,180)'></i>
          <span class="">Signup</span>
        </a>


        {% endif %}
      </div>
    </div>
  </div>
  <div class="p-16 ml-40">
    {% block body %}Default{% endblock %}
  </div>
  </div>


  {% if request.user.is_authenticated %}
  <div
    class="fixed left-0 top-0 flex h-full w-full items-center justify-center bg-black bg-opacity-60 py-10 hidden js-modal"
    id="create">
    <div class="max-h-full w-full max-w-xl overflow-y-auto sm:rounded-2xl bg-white">
      <div class="w-full">
        <div class="m-8 my-20 max-w-[400px] mx-auto">
          <div class="mb-8">
            <h1 class="mb-4 text-3xl font-extrabold">New Post</h1>
            <div class="mb-4">
              <textarea class="border-2 border-teal-500 my-4 w-full js-post-text" rows="4"
                placeholder="Write Your Thoughts" maxlength="240" data-post-url={% url "feed:create" %}></textarea>
            </div>
          </div>
          <div class="space-y-4">
            <button class="p-3 rounded-full text-white w-full font-semibold js-submit"
              style="background-color: rgba(0, 255, 206)">Submit</button>
            <button class="p-3 bg-white border rounded-full w-full font-semibold modal-click">Cancel</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</div>

  <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/create.html
{% extends "base.html" %}


{% block title %}New Post{% endblock %}


{% block body %}
    <form method="POST" action=".">
    {% csrf_token %}
    {{form.as_p}}        
    <button type="submit" class="group relative h-12 w-48 overflow-hidden rounded-2xl bg-teal-500 text-lg font-bold text-white">
      Hover me!
      <div class="absolute inset-0 h-full w-full scale-0 rounded-2xl transition-all duration-300 group-hover:scale-100 group-hover:bg-white/30"></div>
    </button>
    </form>
{% endblock %}

templates/detail.html
{% extends "base.html" %}
{% load thumbnail %}


{% block title %}{{ post.text }} by {{ post.author.username }}{% endblock %}


{% block body %}
    <!-- component is from  -->
    {% include "includes/post.html" with post=post %}
        
{% endblock %}

    

templates/homepage.html
{% extends "base.html" %}



{% block title %}Home{% endblock %}
{% block style %}
    <script src="https://unpkg.com/htmx.org@1.9.6" integrity="sha384-FhXw7b6AlE/jyjlZH5iHa/tTe9EpJ1Y55RjcgPbjeWMskSxZt1v9qkxLJWNJaGni" crossorigin="anonymous"></script>
    <style>
        #posts-container{
            margin-left: 40px;
        }
    </style>
{% endblock %}

{% block body %}
    <div id="posts-container">

        {% if messages %}
                {% for message in messages %}
                <div class="bg-gradient-to-r from-green-400 to-blue-500 text-center text-black py-1">
                        {{message}}
                    </div>
                {% endfor %}
            </ul>
        {% endif %}

        {% if not posts %}
            Explore and Follow someone
        {% else %}
        <div id="posts">
            {% for post in posts %}
                <div class="articles"> 
                    {% include "includes/post.html" with post=post detail_on=True %}

                    {% if posts.has_next and forloop.last %}
                    <span hx-get="{% url 'feed:index' %}?page={{ posts.next_page_number }}"
                        hx-swap="beforeend" hx-target="#posts" hx-select=".articles"
                        hx-trigger="revealed">
                        </span>

                    {% endif %}
                </div>
            {% endfor %}    
            </div>
        {% endif %}
    </div>
{% endblock %}

    